export default [
  {
    name: "Jarcase",
    info: "Custom Phone Case for iPhone and Samsung Galaxy",
    url: "https://jarcase.com/",
    screenshots: "jarcase.com.jpg",
    tech_stack: ["WooCommerce", "Mailchimp"],
  },
  {
    name: "Mewlena Shop",
    info: "Distributor Resimi Yessana & Quail Hijab",
    url: "https://mewlena.com/",
    screenshots: "mewlena.com.jpg",
    tech_stack: ["Hugo", "Google Cloud"],
  },
  {
    name: "SK Media",
    info: "Jasa Pembuatan Video Company Profile",
    url: "https://skmedia.id/",
    screenshots: "skmedia.id.jpeg",
    tech_stack: ["WordPress", "Elementor"],
  },
  {
    name: "Voice Me",
    info: "Influencer Marketing Agency Jakarta",
    url: "https://voiceme.co.id/",
    screenshots: "voiceme.co.id.jpeg",
    tech_stack: ["WordPress", "Elementor"],
  },
  {
    name: "Caseshunter",
    info: "Custom Phone Case Caseshunter",
    url: "https://www.caseshunter.com/",
    screenshots: "caseshunter.com.jpg",
    tech_stack: ["BigCommerce"],
  },
  {
    name: "dilayout",
    info: "Jasa Layout Buku, Majalah, Jurnal, dan Design Cover",
    url: "https://dilayout.com/",
    screenshots: "dilayout.com.jpg",
    tech_stack: ["WordPress"],
  },
  {
    name: "dejavain",
    info: "Print-on-Demands T-shirts",
    url: "https://dejavain.com/",
    screenshots: "dejavain.com.jpg",
    tech_stack: ["BigCommerce"],
  },
  {
    name: "Sulur",
    info: "Penerbit dan Percetakan Buku Terbaik di Yogyakarta",
    url: "https://sulur.co.id/",
    screenshots: "sulur.co.id.jpg",
    tech_stack: ["WooCommerce"],
  },
  {
    name: "Halal Tren",
    info: "Kesempurnaan Gaya Hidup",
    url: "https://halaltren.com/",
    screenshots: "halaltren.com.jpg",
    tech_stack: ["WordPress"],
  },
  {
    name: "Didaksi",
    info: "Sumber Informasi bagi Para Guru, Orang Tua, dan Peneliatan Pendidikan Anak Usia Dini (PAUD)",
    url: "https://didaksi.com/",
    screenshots: "didaksi.com.jpg",
    tech_stack: ["WordPress"],
  },
  {
    name: "SDS Institute",
    info: "Lembaga Strategi Pembangunan Berkelanjutan",
    url: "https://sdsinstitute.org/",
    screenshots: "sdsinstitute.org.jpg",
    tech_stack: ["WordPress", "Elementor"],
  },
];
